### ISSUE TITLE
Visualize Release frequency

### ISSUE THREAD

**Issue by hpbl** [hpbl/OnboardingVisualization#17]
| Index | Data | Possible ways to obtain it | Visualization | 
|---|---|---|---|
| 6 | Release frequency | Just watch the frenquency | [Timeline](https://datavizcatalogue.com/methods/donut_chart.html) and Numeric|

A timeline where each event is a release. It will work better if the space between the releases is measurable.

Also we could show numerically "A release every X hours" and then give comparisons with data from companies, for example: Everytime you release, there are 7 new updates to facebook.

_Originally posted by @hpbl in https://github.com/hpbl/OnboardingVisualization/issues/4#issuecomment-439882523_

**Comment by rfl3** [comment]
https://bl.ocks.org/danbjoseph/13d9365450c27ed3bf5a568721296dcc
