### ISSUE TITLE
Indentify which data will be used

### ISSUE THREAD

**Issue by hpbl** [hpbl/OnboardingVisualization#2]

**Comment by rfl3** [comment]
# Data that will be relevant to visualize

| Data | Ways to obtain it |
|---|---|
| Issues related to the ReadME (tutorial) | Create tutorial labels or use an NLP to find out |
| Read the ReadME file to find how many steps the tutorial have | Use an NLP |
| Number of PRs oppened by new contributors | Discover if it's the first PR of the user |
| How many of these first PRs were accepted | Just see if it was accepted |
| How many of these first PRs went into production | recommend CI/CD |
| Release frequency | Just watch the frenquency |
| Number of requested changes on PRs | Requested changes by PRs|
| Number of accepted PRs after changes were required | Just watch the PRs |
| Number of forks resulted into PRs | Get number of forks and divide by number of first PRs |
| How much time does it take to accept a PR | Just take the time to a PR be accepted |
| How much time does it take to review a PR | Just take the time to a PR be reviewd |
| How many PRs are open and needing review | Get PRs oppened and watch for reviews |

**Comment by hpbl** [comment]
@rrbarioni please review to make sure that the data covers everything we need, and if there's still data worth acquiring. If everything is okay, please move card to done.

**Comment by rrbarioni** [comment]
All okay!
