### ISSUE TITLE
Define which visualizations better exposes the raised issues

### ISSUE THREAD

**Issue by rrbarioni** [hpbl/OnboardingVisualization#4]
# Data that will be relevant to visualize

| Index | Data | Possible ways to obtain it | Visualization | 
|---|---|---|---|
| 1 | Issues related to the ReadME (tutorial) | Create tutorial labels or use an NLP to find out |
| 2 | Read the ReadME file to find how many steps the tutorial have | Use an NLP |
| 3 | Number of PRs oppened by new contributors | Discover if it's the first PR of the user |
| 4 | How many of these first PRs were accepted | Just see if it was accepted |
| 5 | How many of these first PRs went into production | recommend CI/CD |
| 6 | Release frequency | Just watch the frenquency |
| 7 | Number of requested changes on PRs | Requested changes by PRs|
| 8 | Number of accepted PRs after changes were required | Just watch the PRs |
| 9 | Number of forks resulted into PRs | Get number of forks and divide by number of first PRs |
| 10 | How much time does it take to accept a PR | Just take the time to a PR be accepted |
| 11 | How much time does it take to review a PR | Just take the time to a PR be reviewed |
| 12 | How many PRs are open and needing review | Get PRs oppened and watch for reviews |

Describe which visualization will be used, and why.

**Comment by hpbl** [comment]
# Data that will be relevant to visualize

| Data | Ways to obtain it |
|---|---|
| Issues related to the ReadME (tutorial) | Create tutorial labels or use an NLP to find out |
| Read the ReadME file to find how many steps the tutorial have | Use an NLP |
| Number of PRs oppened by new contributors | Discover if it's the first PR of the user |
| How many of these first PRs were accepted | Just see if it was accepted |
| How many of these first PRs went into production | recommend CI/CD |
| Release frequency | Just watch the frenquency |
| Number of requested changes on PRs | Requested changes by PRs|
| Number of accepted PRs after changes were required | Just watch the PRs |
| Number of forks resulted into PRs | Get number of forks and divide by number of first PRs |
| How much time does it take to accept a PR | Just take the time to a PR be accepted |
| How much time does it take to review a PR | Just take the time to a PR be reviewd |
| How many PRs are open and needing review | Get PRs oppened and watch for reviews |

**Comment by hpbl** [comment]
# Visualize Issues related to the ReadME (tutorial)

| Index | Data | Possible ways to obtain it | Visualization |
|---|---|---|---|
| 1 | Issues related to the ReadME (tutorial) | Create tutorial labels or use an NLP to find out | [Donut Chart](https://datavizcatalogue.com/methods/donut_chart.html) |

With a donut chart we can see proportionally how many issues related to the README were open, in relation to the total amount of issues. This way we can see if the README has been a big problem as a whole to the repo.

**Comment by hpbl** [comment]
# Visualize Number of PRs opened by new contributors

| Index | Data | Possible ways to obtain it | Visualization | 
|---|---|---|---|
| 3 | Number of PRs oppened by new contributors | Discover if it's the first PR of the user |
| 4 | How many of these first PRs were accepted | Just see if it was accepted |  [Donut Chart](https://datavizcatalogue.com/methods/donut_chart.html)

A donut chart showing how many PRs were opened by new contributors (the first PR by the user). Each section of the donut will show how many were accepted, rejected, or are open (waiting for review).

**Comment by hpbl** [comment]
# Visualize Number of PRs opened by new contributors

| Index | Data | Possible ways to obtain it | Visualization | 
|---|---|---|---|
| 3 | Number of PRs oppened by new contributors | Discover if it's the first PR of the user |
| 4 | How many of these first PRs were accepted | Just see if it was accepted |  [Donut Chart](https://datavizcatalogue.com/methods/donut_chart.html)
| 5 | How many of these first PRs went into production | recommend CI/CD |

This one is tricky as we don't really know if the repo has CI/CD implemented. We might suggest that they implement as a good practice.

If we have the info of if the PR is in production, a donut chart of the approved PRs with a section for the ones on production.

**Comment by hpbl** [comment]
# Release frequency

| Index | Data | Possible ways to obtain it | Visualization | 
|---|---|---|---|
| 6 | Release frequency | Just watch the frenquency | [Timeline](https://datavizcatalogue.com/methods/donut_chart.html) and Numeric|

A timeline where each event is a release. It will work better if the space between the releases is measurable.

Also we could show numerically "A release every X hours" and then give comparisons with data from companies, for example: Everytime you release, there are 7 new updates to facebook.

**Comment by hpbl** [comment]
# Visualize Number of requested changes on PRs

| Index | Data | Possible ways to obtain it | Visualization | 
|---|---|---|---|
| 7 | Number of requested changes on PRs | Requested changes by PRs| [Interactive Histogram](https://datavizcatalogue.com/methods/histogram.html) |

This visualization should show how frictionless it is to have a PR accepted on the repo.

We could have a histogram where on the Y axis lies the number of PRs, and on the X axis the number of times where changes were requested on the PR.

Since the PRs will be grouped on the bins, clicking a bin should reveal below or beside the graph a list showing each PR, preferably with a link to it, so the maintainer can see what happened.

**Comment by rrbarioni** [comment]
Index | Data | Possible ways to obtain it | Visualization
-- | -- | -- | --
8 | Number of accepted PRs after changes were required | Just watch the PRs | Interactive Histogram

Could be a visualization close related to "Number of requested changes on PRs", so that we could visualize the proportion of accepted PRs, given the number of required changes.

**Comment by rrbarioni** [comment]
Index | Data | Possible ways to obtain it | Visualization
-- | -- | -- | --
9 | Number of forks resulted into PRs | Get number of forks and divide by number of first PRs | Interactive Histogram

Similar to the "Number of accepted PRs after changes were required" visualization, we could visualize the proportion of requested PRs, given the number of forks.

**Comment by rrbarioni** [comment]
Index | Data | Possible ways to obtain it | Visualization
-- | -- | -- | --
10 | How much time does it take to accept a PR | Just take the time to a PR be accepted | Density Plot |  
11 | How much time does it take to review a PR | Just take the time to a PR be reviewed | Density Plot |

As time is a continuous variable, we could visualize those amounts as time varies (10 and 11 could be visualized together)

**Comment by rfl3** [comment]
# Visualize general PRs for the repository

| Index | Data | Possible ways to obtain it | Visualization |
|---|---|---|---|
| 12 | How many PRs are open and needing review | Get PRs oppened and watch for reviews | [Donut Chart](https://datavizcatalogue.com/methods/donut_chart.html) |

Follow the same logic of [this](https://github.com/hpbl/OnboardingVisualization/issues/4#issuecomment-439728712) solution. But generalize all contributors.
