### ISSUE TITLE
Study ways to obtain the data

### ISSUE THREAD

**Issue by rfl3** [hpbl/OnboardingVisualization#5]
# Data that will be relevant to visualize

| Index | Data | Possible ways to obtain it |
|---|---|---|
| 1 | Issues related to the ReadME (tutorial) | Create tutorial labels or use an NLP to find out |
| 2 | Read the ReadME file to find how many steps the tutorial have | Use an NLP |
| 3 | Number of PRs oppened by new contributors that were accepted | Get the first PR of each author and see if it was accepted |
| 4 | Number of PRs oppened by new contributors that went into production | recommend CI/CD |
| 5 | Release frequency | Just watch the frenquency |
| 6 | Number of requested changes on PRs | Requested changes by PRs|
| 7 | Number of accepted PRs after changes were required | Just watch the PRs |
| 8 | Number of forks resulted into PRs | Get number of forks and divide by number of first PRs |
| 9 | How much time does it take to accept a PR | Just take the time to a PR be accepted |
| 10 | How much time does it take to review a PR | Just take the time to a PR be reviewd |
| 11 | How many PRs are open and needing review | Get PRs oppened and watch for reviews |

We need to decide which way will be use to acquire the data, if we can get through the API, of if a crawler is needed. Either way, describe how the data will be acquired, with links.

**Comment by hpbl** [comment]
teste

**Comment by MVictorM** [comment]
**1. Issues related to the ReadME (tutorial)** 
https://developer.github.com/v3/issues/#list-issues
check if the body or title contains the word READ.md

**Comment by MVictorM** [comment]
**2. Read the README file to find how many steps the tutorial have**
Get the content of README.md passing filename and repo name to de API and use it in a NLP
https://developer.github.com/v3/search/#search-code

**Comment by MVictorM** [comment]
**4. Number of PRs oppened by new contributors that went into production**
https://developer.github.com/v3/pulls/#list-pull-requests
We can get the difference between open and merged PRs

**Comment by rfl3** [comment]
**8. Just watch the PRs**
Get the PRs filtered by the number **7** and check if the reviews after the REQUEST_CHANGES found have the event of APPROVE.

**Comment by rfl3** [comment]
**9. Get number of forks and divide by number of first PRs**
Get the first PRs got in number **3** and divide by the number of forks obtained on the fork_counts
https://developer.github.com/v3/repos/forks/#list-forks

**Comment by MVictorM** [comment]
**5. Release frequency**
https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository
Get the releases list and check dates

**Comment by rfl3** [comment]
**9. Just take the time to a PR be accepted**
Get the difference between created_at and closed_at
https://developer.github.com/v3/pulls/#get-a-single-pull-request

**Comment by rfl3** [comment]
**10. Just take the time to a PR be reviewd**
Get the difference of PR's created_at (**9**) data and the first review not that are not from the PR user (**6**).

**Comment by rfl3** [comment]
**11. Get PRs oppened and watch for reviews**
Get all the Reviews from a PR and check if there's a APPROVED (**6**).

**Comment by rfl3** [comment]
@hpbl and @rrbarioni could you check if this is ok? When you're done, move this card to the done column.
Thanks!

**Comment by rrbarioni** [comment]
This is ok!

**Comment by hpbl** [comment]
Done, edited the link to get the README. Everything else seems in order. nice job!
